name: Create Github release
run-name: Creating GH release - ${{ github.ref_name }}

on:
  push:
    tags:
      - '**'

jobs:
  release2:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: 'Create release'
        uses: 'actions/github-script@v5'
        with:
          github-token: ${{secrets.GH_TOKEN}}
          script: |
            github.rest.repos.createRelease({
              draft: false,
              generate_release_notes: false,
              name: '${{ github.ref_name}}',
              owner: context.repo.owner,
              prerelease: false,
              repo: context.repo.repo,
              body: `Please refer to [CHANGELOG.md](https://github.com/nip10/zesty-ui/blob/master/CHANGELOG.md) for details.`,
              tag_name: '${{ github.ref_name}}',
            });
